<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LfMetasManager\Module'                        => __DIR__ . '/Module.php',
    'LfMetasManager\Controller\MetasManagerController' => __DIR__ . '/src/LfMetasManager/Controller/MetasManagerController.php',
    'LfMetasManagerTest\Framework\TestCase'        => __DIR__ . '/tests/LfMetasManager/Framework/TestCase.php',
    'LfMetasManagerTest\SampleTest'                => __DIR__ . '/tests/LfMetasManager/SampleTest.php',
);
